apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
  - port: {{ .Values.service.port | default 4200 }}
    targetPort: {{ .Values.service.targetPort | default 4200 }}
    nodePort: {{ .Values.service.nodePort | default 30000 }}
  selector:
    app: {{ .Release.Name }}
