---
calico_version: "v3.28.0"
canal_version: "latest"
flannel_version: "v0.25.5"
weave_net_version: "v2.8.1"

calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
canal_manifest_url: "https://docs.projectcalico.org/manifests/canal.yaml"
flannel_manifest_url: "https://github.com/flannel-io/flannel/releases/download/{{ flannel_version }}/kube-flannel.yml"
weave_net_manifest_url: "https://github.com/weaveworks/weave/releases/download/{{ weave_net_version }}/weave-daemonset-k8s.yaml"
