---
- name: Ensure containerd is installed
  ansible.builtin.package:
    name: containerd
    state: present
  become: true

- name: Ensure /etc/containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  become: true  

- name: Configure containerd
  ansible.builtin.command: containerd config default
  register: containerd_config

- name: Set value of SystemdCgroup
  ansible.builtin.shell: |
    containerd config default | sudo tee /etc/containerd/config.toml | grep SystemdCgroup
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
    
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  become: true
