- name: Start and enable containerd on CentOS
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Enable and start containerd on Debian
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Start and enable containerd on Ubuntu
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Restart and enable containerd on Fedora
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Restart and enable containerd on RedHat
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
  ignore_errors: true
