---
- name: Include tasks for Debian-based systems
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Include tasks for RedHat-based systems
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
