global:
  multiTenant: true

redis-ha:
  enabled: true
  replicas: 3

server:
  # Merged server configuration
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  service:
    type: NodePort
    nodePort: 30080
  rbacConfig:  # Moved under the same server block
    policy.csv: |
      g, platform-team, role:admin
      g, team-alpha, role:readonly
  # Resource quotas for multi-tenancy (optional)
  # resourceCustomizations: |
  #   argoproj.io/Application:
  #     limit:
  #       memory: 512Mi
  #       cpu: 500m
repoServer:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

applicationSet:
  replicas: 2

controller:
  replicas: 2
  env:
    - name: ARGOCD_CONTROLLER_REPLICAS
      value: "2"
    - name: ARGOCD_CONTROLLER_SHARDING_ALGORITHM
      value: "consistent-hashing"
# # Multi-Tenancy Configuration
# projects:
#   # Example project for team-alpha (repeat for other teams)
#   - name: team-alpha
#     description: Team Alpha Project
#     destinations:
#       - namespace: devops-namespace
#         server: https://kubernetes.default.svc
#     sourceRepos:
#       - https://github.com/m3bdlkawy/DevOps-project/tree/main/helm-chart


# Add ArgoCD Helm repo
helm repo add argo https://argoproj.github.io/argo-helm

# Install in argocd namespace
helm upgrade --install argocd argo/argo-cd \
  --namespace argocd \
  --create-namespace \
  --values argocd-values.yaml
kubectl -n argocd get secret argocd-initial-admin-secret \
  -o jsonpath="{.data.password}" | base64 -d && echo
