global:
  multiTenant: true

redis-ha:
  enabled: true
  replicas: 3 # Minimum for true HA
  haproxy:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

server:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: NodePort
    nodePort: 30080

repoServer:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

rbacConfig:
  policy.csv: |
    g, admin, role:admin
    # Production recommendation:
    # g, dev-team, role:readonly
    # g, ops-team, role:admin
