apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whitehelment-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/m3bdlkawy/Whitehelment.git
    targetRevision: main
    path: Helm-Charts/app-helm-chart
    helm:
      # Optional: Specify values files from your chart
      valueFiles:
      - values.yaml
      # Optional: Override values
      values: |
        service:
          type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: whitehelment-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
