---
- name: Install Flannel
  ansible.builtin.command: kubectl apply -f {{ flannel_manifest_url }}
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  register: flannel_apply_result
  changed_when: "'configured' in flannel_apply_result.stdout"
