plugin: amazon.aws.aws_ec2
regions:
- us-east-1
hostnames:
- ip-address
- public-ip-address
- private-ip-address
keyed_groups:
- key: tags.Name
  prefix: ""
  separator: ""

compose:
  ansible_host: public_ip_address | default(private_ip_address)
  ansible_user: "ubuntu"
