- hosts: aws_ec2
  become: true
  gather_facts: true

  roles:
  - role: containerd
  - role: common
  - role: kubernetes

- hosts: master
  become: true
  gather_facts: true

  roles:
  - role: master
  - role: cni

- hosts: worker
  become: true
  gather_facts: true
  roles:
  - role: worker
